---
- name: Remove build deps
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes
  with_items: "{{ redis_build_deps }}"

- name: Remove sources
  file:
    path: "{{ redis_sources_dir }}"
    state: absent
