---
- name: Install group and user
  import_tasks: user.yml

- name: Install build deps
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ redis_build_deps }}"

- name: Install redis
  import_tasks: install.yml

- name: Cleanup
  import_tasks: cleanup.yml
